/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salone.view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.salone.Controller.CatogeryController;
import lk.ijse.salone.Model.Catogery;

/**
 *
 * @author Lakshika
 */
public class CatogeryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CatogeryPanel
     */
    public CatogeryPanel() {
        try {
            initComponents();
            jPanel1.setBackground(new Color(0,0,0,40));
            jPanel2.setBackground(new Color(0,0,0,40));
            jPanel6.setBackground(new Color(0,0,0,40));
            jPanel3.setBackground(new Color(0,0,0,120));
            loadAllCatogery();
           generateCatogeryId();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CatogeryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CatogeryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCatogeryId = new javax.swing.JTextField();
        txtCatogeryName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Grid_2_65px.png"))); // NOI18N
        jLabel3.setText("Manage Category");
        jLabel3.setIconTextGap(20);
        add(jLabel3);
        jLabel3.setBounds(20, 10, 460, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Catogery ID");
        add(jLabel9);
        jLabel9.setBounds(40, 200, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Catogery Name ");
        add(jLabel6);
        jLabel6.setBounds(40, 260, 180, 40);

        txtCatogeryId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCatogeryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatogeryIdActionPerformed(evt);
            }
        });
        add(txtCatogeryId);
        txtCatogeryId.setBounds(230, 210, 370, 40);

        txtCatogeryName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCatogeryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatogeryNameActionPerformed(evt);
            }
        });
        add(txtCatogeryName);
        txtCatogeryName.setBounds(230, 260, 430, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Search_45px_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 50, 40));

        add(jPanel1);
        jPanel1.setBounds(10, 170, 690, 160);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Catogery ID", "Catogery Name"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 690, 170));

        add(jPanel2);
        jPanel2.setBounds(10, 480, 730, 220);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        add(jPanel3);
        jPanel3.setBounds(0, 0, 1080, 80);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1);
        jSeparator1.setBounds(10, 430, 1040, 10);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Available_Updates_45px.png"))); // NOI18N
        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 50));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Trash_Can_40px.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 50));

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Add_New_40px_1.png"))); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 50));

        add(jPanel6);
        jPanel6.setBounds(720, 170, 210, 190);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        add(jPanel7);
        jPanel7.setBounds(0, 560, 10, 64);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCatogeryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatogeryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatogeryIdActionPerformed

    private void txtCatogeryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatogeryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatogeryNameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
        try {
            Catogery c1=new Catogery();
            c1.setCat_ID(txtCatogeryId.getText());
            c1.setCat_Name(txtCatogeryName.getText());
            
            boolean isSaved=new CatogeryController().saveCatogery(c1);
            if(isSaved){
                JOptionPane.showMessageDialog(null,"saved Successfully"); loadAllCatogery();
            }else{
                  JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //Logger.getLogger(CatogeryPanel.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row = tbl.getSelectedRow();
        txtCatogeryId.setText((String) tbl.getValueAt(row, 0));
        txtCatogeryName.setText((String) tbl.getValueAt(row, 1));
    }//GEN-LAST:event_tblMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Catogery c1=new CatogeryController().searchCatogery(txtCatogeryId.getText());
            if(c1 !=null){
                
                 txtCatogeryId.setText(c1.getCat_ID());
                txtCatogeryName.setText(c1.getCat_Name());
                
                
                
            }else{
                  JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
           // Logger.getLogger(CatogeryPanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            boolean isDelete=new CatogeryController().deleteCatogery(txtCatogeryId.getText());
            if(isDelete){
                 JOptionPane.showMessageDialog(null,"Deleted Successfully");
                 loadAllCatogery();
            }else{
                   JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
          // Logger.getLogger(CatogeryPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Catogery c1=new Catogery();
            c1.setCat_ID(txtCatogeryId.getText());
            c1.setCat_Name(txtCatogeryName.getText());
            
            boolean isUpdate=new CatogeryController().updateCatogery(c1);
            if(isUpdate){
                  JOptionPane.showMessageDialog(null,"Updated Successfully"); loadAllCatogery(); 
            }else{
                   JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //Logger.getLogger(CatogeryPanel.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCatogeryId;
    private javax.swing.JTextField txtCatogeryName;
    // End of variables declaration//GEN-END:variables

    private void loadAllCatogery() throws ClassNotFoundException, SQLException {
        ArrayList<Catogery>list=new CatogeryController().getCatogery();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
         model.setRowCount(0);
        for (Catogery catogery : list) {
            Object[]rowData={catogery.getCat_ID(),catogery.getCat_Name()};
            model.addRow(rowData);
        }
    }

    private void generateCatogeryId() throws ClassNotFoundException, SQLException {
        String s1=new CatogeryController().generateCatogeryId();
        txtCatogeryId.setText(s1);
    }
}
