/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salone.view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.salone.Controller.CustomerController;
import lk.ijse.salone.Model.Customer;

/**
 *
 * @author Lakshika
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        try {
            initComponents();
            jPanel1.setBackground(new Color(0,0,0,40));
            jPanel2.setBackground(new Color(0,0,0,120));
            jPanel3.setBackground(new Color(0,0,0,40));
            jPanel4.setBackground(new Color(0,0,0,40));
            generateCustomerId();
            loadAllCustomer();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtCustomerNo = new javax.swing.JTextField();
        txtCustomerId = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1066, 768));
        setPreferredSize(new java.awt.Dimension(1066, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Customer ID ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, 40));

        txtCustomerNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCustomerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNoActionPerformed(evt);
            }
        });
        add(txtCustomerNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 430, 40));

        txtCustomerId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });
        add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 370, 40));

        txtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 430, 40));

        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAddressActionPerformed(evt);
            }
        });
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 430, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Mobile No    ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Customer Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Customer Name  ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Search_45px_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 60, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 700, 230));

        tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus_ID", " Name", "Address", "Mobile No"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 960, 180));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Customer_65px.png"))); // NOI18N
        jLabel3.setText("Manage Customer");
        jLabel3.setIconTextGap(20);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 490, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 80));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 990, 220));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1020, 10));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Trash_Can_40px.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 50));

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Add_New_40px_1.png"))); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Available_Updates_45px.png"))); // NOI18N
        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 50));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 190, 190));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 10, 64));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNoActionPerformed

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAddressActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Customer c1=new Customer();
            c1.setCus_ID(txtCustomerId.getText());
            c1.setCus_Name(txtCustomerName.getText());
            c1.setCus_Address(txtCustomerAddress.getText());
            c1.setCus_TP(Integer.parseInt(txtCustomerNo.getText()));
            boolean isSaved= new CustomerController().saveCustomer(c1);
            if(isSaved){
                JOptionPane.showMessageDialog(null,"Saved Successfully");loadAllCustomer();
            }else{
                 JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
           // Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row = tbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        
       
        txtCustomerId.setText((String) model.getValueAt(row, 0));
         txtCustomerName.setText((String) model.getValueAt(row, 1));
          txtCustomerAddress.setText((String) model.getValueAt(row, 2));
           txtCustomerNo.setText( model.getValueAt(row, 3)+"");
    }//GEN-LAST:event_tblMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
        try {  
            boolean isDelete=new CustomerController().deleteCustomer(txtCustomerId.getText());
            if(isDelete){
                  JOptionPane.showMessageDialog(null, "Deleted Successfully");loadAllCustomer();
            }else{
                JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
          //  Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Customer c1=new Customer();
            c1.setCus_ID(txtCustomerId.getText());
            c1.setCus_Name(txtCustomerName.getText());
            c1.setCus_Address(txtCustomerAddress.getText());
            c1.setCus_TP(Integer.parseInt(txtCustomerNo.getText()));
            
            boolean isUpdate=new CustomerController().updateCustomer(c1);
            if(isUpdate){
                JOptionPane.showMessageDialog(null, "Updated Succesfully");loadAllCustomer();
            }else{
               JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (Exception ex) {
           // Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
     
     
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ArrayList<Customer>list= new CustomerController().searchCustomer(txtCustomerId.getText());
            if(list!=null){
                for (Customer customer : list) {
                    txtCustomerId.setText(customer.getCus_ID());
                    txtCustomerName.setText(customer.getCus_Name());
                    txtCustomerAddress.setText(customer.getCus_Address());
                    txtCustomerNo.setText(customer.getCus_TP()+"");
                }}
            } catch (Exception ex) {
               // Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
            } 

    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerNo;
    // End of variables declaration//GEN-END:variables

    private void generateCustomerId() throws ClassNotFoundException, SQLException {
      String id= new CustomerController().generateId();
      txtCustomerId.setText(id);
    }

    private void loadAllCustomer() throws SQLException, ClassNotFoundException {
      ArrayList<Customer>list= new CustomerController().getCustomers();
        
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
         model.setRowCount(0);
        for (Customer customer : list) {
            Object[]rowData={
            customer.getCus_ID(),customer.getCus_Name(),customer.getCus_Address(),customer.getCus_TP()
            
            };
            model.addRow(rowData);
        }
      
      
    }
}
