/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salone.view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.salone.Controller.EmployeeController;
import lk.ijse.salone.Model.Employee;

/**
 *
 * @author Lakshika
 */
public class EmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    public EmployeePanel() {
        try {
            initComponents();
            jPanel1.setBackground(new Color(0,0,0,40));
            jPanel2.setBackground(new Color(0,0,0,40));
            jPanel6.setBackground(new Color(0,0,0,40));
            jPanel3.setBackground(new Color(0,0,0,120));
            generateEmployeeId();
            loadEmployee();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmployeeMobile = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeeAddress = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtEmployeeAge = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Mobile   ");
        add(jLabel5);
        jLabel5.setBounds(40, 370, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Employee ID  ");
        add(jLabel6);
        jLabel6.setBounds(40, 180, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Employee Name ");
        add(jLabel7);
        jLabel7.setBounds(40, 220, 180, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Address      ");
        add(jLabel9);
        jLabel9.setBounds(40, 270, 160, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Age           ");
        add(jLabel10);
        jLabel10.setBounds(40, 320, 160, 40);

        txtEmployeeMobile.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeMobileActionPerformed(evt);
            }
        });
        add(txtEmployeeMobile);
        txtEmployeeMobile.setBounds(230, 380, 430, 40);

        txtEmployeeId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });
        add(txtEmployeeId);
        txtEmployeeId.setBounds(230, 180, 370, 40);

        txtEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNameActionPerformed(evt);
            }
        });
        add(txtEmployeeName);
        txtEmployeeName.setBounds(230, 230, 430, 40);

        txtEmployeeAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeAddressActionPerformed(evt);
            }
        });
        add(txtEmployeeAddress);
        txtEmployeeAddress.setBounds(230, 280, 430, 40);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        add(jPanel7);
        jPanel7.setBounds(0, 500, 10, 64);

        txtEmployeeAge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeAgeActionPerformed(evt);
            }
        });
        add(txtEmployeeAge);
        txtEmployeeAge.setBounds(230, 330, 430, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Search_45px_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 60, 40));

        add(jPanel1);
        jPanel1.setBounds(10, 160, 690, 280);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Construction_Worker_65px.png"))); // NOI18N
        jLabel3.setText("Manage Employee");
        jLabel3.setIconTextGap(20);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(jPanel3);
        jPanel3.setBounds(0, 0, 1080, 80);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus_ID", " Name", "Address", "age", "Tele No"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 980, 210));

        add(jPanel2);
        jPanel2.setBounds(10, 470, 1020, 240);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Available_Updates_45px.png"))); // NOI18N
        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 50));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Trash_Can_40px.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 50));

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Add_New_40px_1.png"))); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 50));

        add(jPanel6);
        jPanel6.setBounds(720, 230, 210, 210);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1);
        jSeparator1.setBounds(10, 450, 1040, 2);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeMobileActionPerformed

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void txtEmployeeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeAddressActionPerformed

    private void txtEmployeeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeAgeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Employee e1=new Employee();
            e1.setEmp_ID(txtEmployeeId.getText());
            e1.setEmp_Name(txtEmployeeName.getText());
            e1.setEmp_Address(txtEmployeeAddress.getText());
            e1.setEmp_Age(Integer.parseInt(txtEmployeeAge.getText()));
            e1.setEmp_TP(Integer.parseInt(txtEmployeeMobile.getText()));
            
            boolean isSaved=new EmployeeController().getEmployees(e1);
            
            if(isSaved){
                JOptionPane.showMessageDialog(null, "Saved Successfully ");loadEmployee();
            }else{
                JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            } } catch (Exception ex) {
           // Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Employee e1= new EmployeeController().searchEmployee(txtEmployeeId.getText());
            if(e1!=null){
                txtEmployeeId.setText(e1.getEmp_ID());
                 txtEmployeeName.setText(e1.getEmp_Name());
                  txtEmployeeAddress.setText(e1.getEmp_Address());
                   txtEmployeeAge.setText(e1.getEmp_Age()+"");
                    txtEmployeeMobile.setText(e1.getEmp_TP()+"");
            }else{
                JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
           // Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Employee e1=new Employee();
            e1.setEmp_ID(txtEmployeeId.getText());
            e1.setEmp_Name(txtEmployeeName.getText());
            e1.setEmp_Address(txtEmployeeAddress.getText());
            e1.setEmp_Age(Integer.parseInt(txtEmployeeAge.getText()));
            e1.setEmp_TP(Integer.parseInt(txtEmployeeMobile.getText()));
            
            boolean isUpdate=new EmployeeController().updateEmployee(e1);
            if(isUpdate){
                  JOptionPane.showMessageDialog(null,"Updated Successfully");loadEmployee();
            }else{
                  JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (Exception ex) {
           // Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            boolean isDelete=new EmployeeController().deleteEmployee(txtEmployeeId.getText());
            if(isDelete){
                JOptionPane.showMessageDialog(null,"Deleted Successfully");loadEmployee();
            }else{
                 JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //Logger.getLogger(EmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        }
       
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row = tbl.getSelectedRow();
       
                 txtEmployeeId.setText((String) tbl.getValueAt(row,0));
                 txtEmployeeName.setText((String) tbl.getValueAt(row,1));
                  txtEmployeeAddress.setText((String) tbl.getValueAt(row,2));
                   txtEmployeeAge.setText(tbl.getValueAt(row,3).toString());
                    txtEmployeeMobile.setText(tbl.getValueAt(row,4).toString());
    }//GEN-LAST:event_tblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtEmployeeAddress;
    private javax.swing.JTextField txtEmployeeAge;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeeMobile;
    private javax.swing.JTextField txtEmployeeName;
    // End of variables declaration//GEN-END:variables

    private void generateEmployeeId() throws ClassNotFoundException, SQLException {
       String s1= new EmployeeController().generateId();
       txtEmployeeId.setText(s1);
    }

    private void loadEmployee() throws ClassNotFoundException, SQLException {
       ArrayList<Employee>list= new EmployeeController().loadEmployee();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
         model.setRowCount(0);
        for (Employee employee : list) {
            Object[]rowData={employee.getEmp_ID(),employee.getEmp_Name(),employee.getEmp_Address(),
                employee.getEmp_Age(),employee.getEmp_TP()};
            model.addRow(rowData);
        }
    }
}
