/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salone.view;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.salone.Controller.CatogeryController;
import lk.ijse.salone.Controller.EmployeeController;
import lk.ijse.salone.Controller.ReportController;
import lk.ijse.salone.Controller.ServiceController;
import lk.ijse.salone.Model.Service;

/**
 *
 * @author Lakshika
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        try {
            initComponents();
            jPanel4.setBackground(new Color(0,0,0,120));
            jPanel1.setBackground(new Color(0,0,0,40));
            loadDateAndTime();
            loadAllDailyIncome();
            loadAllMonthlyIncome();
            loadAllYearlyIncome();
            loadEmployeeId();
            loadCatogeryId();
           
        } catch (Exception ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AllIncomeMonthly = new javax.swing.JTextField();
        txtCatogeryIncomeYearly = new javax.swing.JTextField();
        txtCatogeryIncomeMonthly = new javax.swing.JTextField();
        txtServiceIncomeMonthly = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmployeeMonthly = new javax.swing.JTextField();
        txtServiceIncomeYearly = new javax.swing.JTextField();
        AllIncomeYearly = new javax.swing.JTextField();
        txtEmployeeIncomeYearly = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AllIncomeDaily = new javax.swing.JTextField();
        txtEmployeeDaily = new javax.swing.JTextField();
        txtCatogeryIncomeDaily = new javax.swing.JTextField();
        cmbEmployeeId = new javax.swing.JComboBox<>();
        cmbCatogeryId = new javax.swing.JComboBox<>();
        cmbServiceId = new javax.swing.JComboBox<>();
        txtServiceIncomeDaily = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtservice = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Combo_Chart_65px.png"))); // NOI18N
        jLabel3.setText("Reports");
        jLabel3.setIconTextGap(20);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 160, 40));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 10, 64));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 130, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 80));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AllIncomeMonthly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AllIncomeMonthly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(AllIncomeMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 200, 40));

        txtCatogeryIncomeYearly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCatogeryIncomeYearly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtCatogeryIncomeYearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 200, 40));

        txtCatogeryIncomeMonthly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCatogeryIncomeMonthly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtCatogeryIncomeMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 200, 40));

        txtServiceIncomeMonthly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServiceIncomeMonthly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtServiceIncomeMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 200, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Yearly");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 120, 60));

        txtEmployeeMonthly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeMonthly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtEmployeeMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 200, 40));

        txtServiceIncomeYearly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServiceIncomeYearly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtServiceIncomeYearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 200, 40));

        AllIncomeYearly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AllIncomeYearly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(AllIncomeYearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 200, 40));

        txtEmployeeIncomeYearly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeIncomeYearly.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtEmployeeIncomeYearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Monthly");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 170, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Checked_45px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 50, 40));

        AllIncomeDaily.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AllIncomeDaily.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(AllIncomeDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 40));

        txtEmployeeDaily.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmployeeDaily.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtEmployeeDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 40));

        txtCatogeryIncomeDaily.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCatogeryIncomeDaily.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtCatogeryIncomeDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 200, 40));

        cmbEmployeeId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbEmployeeId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEmployeeIdItemStateChanged(evt);
            }
        });
        cmbEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeIdActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 40));

        cmbCatogeryId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCatogeryId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCatogeryIdItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCatogeryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, 40));

        cmbServiceId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbServiceId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbServiceIdItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbServiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 40));

        txtServiceIncomeDaily.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServiceIncomeDaily.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(txtServiceIncomeDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Daily");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 120, 50));

        txtservice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtservice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ALL INCOME ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1010, 490));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Search_45px_2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 60, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeIdActionPerformed
       
    }//GEN-LAST:event_cmbEmployeeIdActionPerformed

    private void cmbEmployeeIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEmployeeIdItemStateChanged
      
        try {
            Double income1=  new ReportController().getEmployeeAlldailyIncome(cmbEmployeeId.getSelectedItem(),txtDate.getText());
            txtEmployeeDaily.setText(income1+"");
            Double income2=  new ReportController().getEmployeeAllMonthlyIncome(cmbEmployeeId.getSelectedItem(),txtDate.getText());
            txtEmployeeMonthly.setText(income2+"");
             Double income3=  new ReportController().getEmployeeAllYearlyIncome(cmbEmployeeId.getSelectedItem(),txtDate.getText());
            txtEmployeeIncomeYearly.setText(income3+"");
            
            
        } catch (Exception ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cmbEmployeeIdItemStateChanged

    private void cmbCatogeryIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCatogeryIdItemStateChanged
        try {
            cmbServiceId.removeAllItems();
            loadServiceId();
            double income1= new ReportController().getCatogeryIncomeDaily(cmbCatogeryId.getSelectedItem(),txtDate.getText());
            txtCatogeryIncomeDaily.setText(income1+"");
            
             double income2= new ReportController().getCatogeryIncomeMonthly(cmbCatogeryId.getSelectedItem(),txtDate.getText());
            txtCatogeryIncomeMonthly.setText(income2+"");
            
             double income3= new ReportController().getCatogeryIncomeYearly(cmbCatogeryId.getSelectedItem(),txtDate.getText());
            txtCatogeryIncomeYearly.setText(income3+"");
        } catch (Exception ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_cmbCatogeryIdItemStateChanged

    private void cmbServiceIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbServiceIdItemStateChanged
      
        
        
    }//GEN-LAST:event_cmbServiceIdItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            double income1= new ReportController().getServiceIncomeDaily(cmbServiceId.getSelectedItem(),txtDate.getText());
              txtServiceIncomeDaily.setText(income1+"");
              
               double income2= new ReportController().getServiceIncomeMonthly(cmbServiceId.getSelectedItem(),txtDate.getText());
              txtServiceIncomeMonthly.setText(income2+"");
              
              double income3= new ReportController().getServiceIncomeYearly(cmbServiceId.getSelectedItem(),txtDate.getText());
              txtServiceIncomeYearly.setText(income3+"");
              
              Service s1 = new ServiceController().getService(cmbServiceId.getSelectedItem().toString());
            
           

            if (s1 != null) {
               
               
                String a = s1.getS_Name();
                txtservice.setText(a);
                System.out.println(a);
            }
              
        } catch (Exception ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            loadAllDailyIncome();
            loadAllMonthlyIncome();
            loadAllYearlyIncome();
            loadEmployeeId();
            loadCatogeryId();
            
               Double income1=  new ReportController().getEmployeeAlldailyIncome(cmbEmployeeId.getSelectedItem(),txtDate.getText());
            txtEmployeeDaily.setText(income1+"");
            Double income2=  new ReportController().getEmployeeAllMonthlyIncome(cmbEmployeeId.getSelectedItem(),txtDate.getText());
            txtEmployeeMonthly.setText(income2+"");
             Double income3=  new ReportController().getEmployeeAllYearlyIncome(cmbEmployeeId.getSelectedItem(),txtDate.getText());
            txtEmployeeIncomeYearly.setText(income3+"");
            
              cmbServiceId.removeAllItems();
            loadServiceId();
            double income11= new ReportController().getCatogeryIncomeDaily(cmbCatogeryId.getSelectedItem(),txtDate.getText());
            txtCatogeryIncomeDaily.setText(income11+"");
            
             double income22= new ReportController().getCatogeryIncomeMonthly(cmbCatogeryId.getSelectedItem(),txtDate.getText());
            txtCatogeryIncomeMonthly.setText(income22+"");
            
             double income33= new ReportController().getCatogeryIncomeYearly(cmbCatogeryId.getSelectedItem(),txtDate.getText());
            txtCatogeryIncomeYearly.setText(income33+"");
            
            
            txtServiceIncomeDaily.setText(null);
             txtServiceIncomeMonthly.setText(null);
              txtServiceIncomeYearly.setText(null);
        } catch (Exception ex) {
           // Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AllIncomeDaily;
    private javax.swing.JTextField AllIncomeMonthly;
    private javax.swing.JTextField AllIncomeYearly;
    private javax.swing.JComboBox<String> cmbCatogeryId;
    private javax.swing.JComboBox<String> cmbEmployeeId;
    private javax.swing.JComboBox<String> cmbServiceId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtCatogeryIncomeDaily;
    private javax.swing.JTextField txtCatogeryIncomeMonthly;
    private javax.swing.JTextField txtCatogeryIncomeYearly;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmployeeDaily;
    private javax.swing.JTextField txtEmployeeIncomeYearly;
    private javax.swing.JTextField txtEmployeeMonthly;
    private javax.swing.JTextField txtServiceIncomeDaily;
    private javax.swing.JTextField txtServiceIncomeMonthly;
    private javax.swing.JTextField txtServiceIncomeYearly;
    private javax.swing.JLabel txtservice;
    // End of variables declaration//GEN-END:variables

    private void loadAllDailyIncome() throws Exception {
      Double income=  new ReportController().getAlldailyIncome(txtDate.getText());
       
      AllIncomeDaily.setText(income+"");
    }

    private void loadDateAndTime() {
       Date date=new Date();
       SimpleDateFormat format1=new SimpleDateFormat("YYYY-MM-dd");
       txtDate.setText(format1.format(date));
       SimpleDateFormat format2=new SimpleDateFormat("HH:mm:ss");
       lblTime.setText(format2.format(date));
    }

    private void loadAllMonthlyIncome() throws Exception {
       Double income=  new ReportController().getMonthlyIncome(txtDate.getText());
       
      AllIncomeMonthly.setText(income+"");
    }

    private void loadAllYearlyIncome() throws Exception{
        Double income=  new ReportController().getYearlyIncome(txtDate.getText());
        AllIncomeYearly.setText(income+"");
    }

    private void loadEmployeeId() throws Exception {
      for (String temp : new EmployeeController().getAllIDS()) {
            cmbEmployeeId.addItem(temp);

        }
    }

    private void loadCatogeryId()throws Exception {
        for (String temp : new CatogeryController().getAllIDS()) {
            cmbCatogeryId.addItem(temp);
        }
    }

    private void loadServiceId() {
        try {
            for (String temp : new ServiceController().getAllIDS(cmbCatogeryId.getSelectedItem().toString())) {

                cmbServiceId.addItem(temp);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddAppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddAppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
