/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.salone.view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.salone.Controller.CatogeryController;
import lk.ijse.salone.Controller.ServiceController;
import lk.ijse.salone.Model.Service;

/**
 *
 * @author Lakshika
 */
public class ServicePanel extends javax.swing.JPanel {

    /**
     * Creates new form ServiceForm
     */
    public ServicePanel() {
        try {
            initComponents();
            
            jPanel1.setBackground(new Color(0,0,0,40));
            jPanel3.setBackground(new Color(0,0,0,40));
            jPanel4.setBackground(new Color(0,0,0,120));
            jPanel5.setBackground(new Color(0,0,0,40));
            loadCatogeryIDS();
            generateServiceID();
            loadAllService();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtServiceDuration = new javax.swing.JTextField();
        cmbCatogery = new javax.swing.JComboBox<>();
        txtServiceId = new javax.swing.JTextField();
        txtServiceName = new javax.swing.JTextField();
        txtServicePrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCatogeryName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Search_45px_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Duration ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Service Price   ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 40));

        txtServiceDuration.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServiceDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceDurationActionPerformed(evt);
            }
        });
        jPanel1.add(txtServiceDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 320, 40));

        cmbCatogery.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCatogery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCatogeryItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCatogery, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 110, 40));

        txtServiceId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtServiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 270, 40));

        txtServiceName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 320, 40));

        txtServicePrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServicePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtServicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 320, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Service Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Catogery Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 40));

        txtCatogeryName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtCatogeryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 210, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Service ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 550, 260));

        tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus_ID", " Name", "Address", "Mobile No", "Title 5"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 980, 230));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Food_Service_65px.png"))); // NOI18N
        jLabel4.setText("Manage Service");
        jLabel4.setIconTextGap(20);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 80));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Trash_Can_40px.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 50));

        jButton8.setBackground(new java.awt.Color(0, 204, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Add_New_40px_1.png"))); // NOI18N
        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/salone/Pictures/icons8_Available_Updates_45px.png"))); // NOI18N
        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 190, 190));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1020, 270));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 10, 64));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1020, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceDurationActionPerformed

    private void txtServiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceIdActionPerformed

    private void txtServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceNameActionPerformed

    private void txtServicePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicePriceActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            Service s1=new Service();
            s1.setCat_ID(cmbCatogery.getSelectedItem().toString());
            s1.setS_ID(txtServiceId.getText());
            s1.setS_Name(txtServiceName.getText());
            s1.setS_Price(Double.parseDouble(txtServicePrice.getText()));
            s1.setS_Duration(Integer.parseInt(txtServiceDuration.getText()));
     
            boolean isSaved=new ServiceController().saveService(s1);
            if(isSaved){
                JOptionPane.showMessageDialog( null, "Saved Successfully");
                txtServiceName.setText("");
                txtServicePrice.setText("");
                txtServiceDuration.setText("");
                generateServiceID();
                loadAllService();
            }else{
                JOptionPane.showMessageDialog( null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (Exception ex) {
           // Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            Service s1= new ServiceController().getServiceById(txtServiceId.getText());
            if(s1!=null){
              txtServiceName.setText(s1.getS_Name());
              txtServicePrice.setText(s1.getS_Price()+"");
              txtServiceDuration.setText(s1.getS_Duration()+"");
              cmbCatogery.setSelectedItem(s1.getCat_ID());
            }else{
                JOptionPane.showMessageDialog(null,"Not Matched","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Service s1=new Service(
                    cmbCatogery.getSelectedItem().toString(),
                    txtServiceId.getText(),
                    txtServiceName.getText(),
                    Double.parseDouble(txtServicePrice.getText()),
                    Integer.parseInt(txtServiceDuration.getText())
            );
            
            boolean isUpdate=new ServiceController().updateService(s1);
            
            if(isUpdate){
                 JOptionPane.showMessageDialog(null, "Updated Successfully");
                  loadAllService();
            }else{
                JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "somethin went wrong","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            boolean isDelete=new ServiceController().deleteService(txtServiceId.getText());
            if(isDelete){
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
                 loadAllService();
            }else{
                 JOptionPane.showMessageDialog(null, "Try again","Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (Exception ex) {
           // Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some thing went wrong","Error", JOptionPane.ERROR_MESSAGE);
        }         
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmbCatogeryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCatogeryItemStateChanged
        try {
            String s1=  new CatogeryController().getCatogeryName(cmbCatogery.getSelectedItem().toString());
            txtCatogeryName.setText(s1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCatogeryItemStateChanged

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row = tbl.getSelectedRow();
               txtServiceId.setText((String) tbl.getValueAt(row, 1));
               txtServiceName.setText((String) tbl.getValueAt(row, 2));
                txtServicePrice.setText( tbl.getValueAt(row, 3)+"");
                txtServiceDuration.setText( tbl.getValueAt(row, 4)+"");
              
            cmbCatogery.setSelectedItem(tbl.getValueAt(row,0));
    }//GEN-LAST:event_tblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCatogery;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCatogeryName;
    private javax.swing.JTextField txtServiceDuration;
    private javax.swing.JTextField txtServiceId;
    private javax.swing.JTextField txtServiceName;
    private javax.swing.JTextField txtServicePrice;
    // End of variables declaration//GEN-END:variables

    private void loadCatogeryIDS() throws ClassNotFoundException, SQLException {
        ArrayList<String> list = new CatogeryController(). getAllIDS();
        for (String string : list) {
            cmbCatogery.addItem(string);
        }
        
        
    }

    private void generateServiceID() throws ClassNotFoundException, SQLException {
      String s1= new ServiceController().generateId();
      txtServiceId.setText(s1);
    }

    private void loadAllService() throws ClassNotFoundException, SQLException {
       ArrayList<Service>list=new ServiceController().getAllService();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        for (Service service : list) {
            Object[]rowData={
            service.getCat_ID(),
            service.getS_ID(),
            service.getS_Name(),
            service.getS_Price(),
            service.getS_Duration()
            
            };
            model.addRow(rowData);
        }
        
    }
}
